export const SET_ARTICLES = 'SET_ARTICLES';
export const SET_ARTICLES_LOADER = 'SET_ARTICLES_LOADER';
export const EDIT_ARTICLE = 'EDIT_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const RESTORE_ARTICLE = 'RESTORE_ARTICLE';

